### ISSUE TITLE
Can I show Alert messages instead of notifications within the application?

### ISSUE THREAD

**Issue by halilozel1903** [giorgosneokleous93/fullscreenintentexample#2]
Greetings, I have defined Reminder. I want to show an Alert message to the user in the application when it is time for the reminder objects. How do I support this?

**Comment by giorgosneokleous93** [comment]
> Greetings, I have defined Reminder. I want to show an Alert message to the user in the application when it is time for the reminder objects. How do I support this?

@halilozel1903 can you please elaborate? Do you want to show the alert when the app is opened or closed?
