### ISSUE TITLE
Why couldn't we display a real fullscreen alert as we could pre Android 10

### ISSUE THREAD

**Issue by omatrot** [giorgosneokleous93/fullscreenintentexample#3]
Hello,
I'm trying to adapt an existing application for Android 10.
We used to switch to an alarm full screen activity (thus interrupting the user) in case of a high importance events.
This seems no more possible with Android 10.
What is your experience?
I thought that we could display a full screen notification, but your sample seems to prove me wrong, in the sense that the notification is not full screen (like an incoming call would?).

**Comment by giorgosneokleous93** [comment]
Hello, 

Full screen intents are expected to work like that. On my phone incoming calls or alarms are not full screen when the phone is active. When the phone is locked or idle the Full screen intent's activity will be used. The notification shown when the phone is active is called heads-up. 

It was never recommended to use activities in such use-cases, but it was enforced recently.

You can check the following resources:
- https://developer.android.com/training/notify-user/time-sensitive
- The blog post attached on the repo, which includes demo videos of the full screen example. https://www.giorgosneokleous.com/2020/03/15/full-screen-intent-notifications-android/

**Comment by omatrot** [comment]
Thanks for the explanation, for me the name is misleading as fullscreen intents are not displayed full screen.
