### ISSUE TITLE
It is not work in Android 11

### ISSUE THREAD

**Issue by poptanai** [giorgosneokleous93/fullscreenintentexample#4]
Hi, the componet is not work in Android 11.

**Comment by giorgosneokleous93** [comment]
Hey,

Are you talking about the lockscreen? It seems that I missed on the AndroidManifest to add to the LockscreenActivity `android:showOnLockScreen="true` and/or `android:showWhenLocked="true"`.

I am away to commit the changes and rectify the blog post. 

Can you please confirm if that works for you?

**Comment by sf99** [comment]
It works, but you need to use special note id for every new note.

**Comment by giorgosneokleous93** [comment]
Edited the Medium article with the fix, thanks @poptanai for finding it out. 

Also, pushed a change [here](https://github.com/giorgosneokleous93/fullscreenintentexample/commit/28865fb3d719d843874771050cc2987340276c84#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cdR50)
