### ISSUE TITLE
Scheduled FullScreenIntent For Locked Screen Android 10 not open if the phone is turned off

### ISSUE THREAD

**Issue by sf99** [giorgosneokleous93/fullscreenintentexample#5]
Hi,
nice project I have learned much from this.
I am testing scheduled fullscreen intent and it do not start when phone - Samsung A51 Android 10 -  is turned off.
I can see sound from notification, but the screen is always off.

I have add 
<activity android:name=".LockScreenActivity"> android:showOnLockScreen="true  android:showWhenLocked="true"       </activity>
but it did not help. 

I am also trying to add some more permissions to manifest, but it also do not help me.

But your similar project works much better - github.com › yuriykulikov › AlarmClock 
I am trying to add some code from your AlarmClock to this project, but I am probably missing something.

What is the different ? What is important to add here to start work from phone, which is turned off ?

Best Regards

Slavomir Fabian

**Comment by sf99** [comment]
What is also interesting, that after new installation and 1. schedule-start it works with phone off - screen is on, but next times screen is always off.

**Comment by sf99** [comment]
After hard mining, I have found that every note id must be different  to works correctly.

**Comment by giorgosneokleous93** [comment]
@sf99 is it working now then? Can I close the ticket?

You can also check out my comment [here](https://github.com/giorgosneokleous93/fullscreenintentexample/issues/4#issuecomment-750441733).
